spring.application.name=portal

spring.datasource.url=jdbc:mysql://loveworld-reports.cbos4aeec90o.ap-south-1.rds.amazonaws.com:3306/loveworld_reports?useSSL=true&requireSSL=true&verifyServerCertificate=false

spring.datasource.username=admin
spring.datasource.password=Loveworld123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialectC:\Users\Sharon\IdeaProjects\portal


server.port=8080
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sharonshelke7@gmail.com
spring.mail.password=teww oqhw pxdc akgf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true