package com.reporting.portal.controller;

import com.reporting.portal.dto.NotificationRequest;
import com.reporting.portal.dto.PaymentRequest;
import com.reporting.portal.entity.Notification;
import com.reporting.portal.entity.Payment;
import com.reporting.portal.service.NotificationService;
import com.reporting.portal.service.PaymentService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/notifications")
@CrossOrigin(origins = "*")
public class NotificationController {

    private final NotificationService notificationService;
    private  final PaymentService paymentService;

    public NotificationController(NotificationService notificationService, PaymentService paymentService) {
        this.notificationService = notificationService;
        this.paymentService = paymentService;
    }

    @PostMapping
    public ResponseEntity<Notification> push(@RequestBody NotificationRequest request) {
        return ResponseEntity.ok(notificationService.push(request));
    }

    @GetMapping
    public ResponseEntity<List<Notification>> getNotifications(
            @RequestParam Long userId,
            @RequestParam String role) {
        return ResponseEntity.ok(notificationService.getNotifications(userId, role));
    }

    @PatchMapping("/{id}/read")
    public ResponseEntity<Notification> markAsRead(@PathVariable Long id) {
        return ResponseEntity.ok(notificationService.markAsRead(id));
    }

    @PatchMapping("/read-all")
    public ResponseEntity<String> markAllAsRead(@RequestParam Long userId) {
        notificationService.markAllAsRead(userId);
        return ResponseEntity.ok("All notifications marked as read");
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<String> delete(@PathVariable Long id) {
        notificationService.deleteNotification(id);
        return ResponseEntity.ok("Notification deleted");
    }
    @PostMapping("/{id}/payment")
    public ResponseEntity<Payment> submitPayment(
            @PathVariable Long id,
            @RequestBody PaymentRequest request) {

        // The request.getPaymentRef() will contain the PayPal Transaction ID
        // e.g. "9G283182A3100234X" generated by PayPal.
        return ResponseEntity.ok(paymentService.submitPayment(id, request));
    }

}